<?php
return [
  'moco_integration_api_key' => [
    'name' => 'moco_integration_api_key',
    'type' => 'String',
    'html_type' => 'password',
    'default' => '',
    'title' => ts('MOCO API Key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Your MOCO API token'),
  ],
  'moco_integration_domain' => [
    'name' => 'moco_integration_domain',
    'type' => 'String',
    'html_type' => 'text',
    'default' => '',
    'title' => ts('MOCO Domain'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Your MOCO subdomain'),
  ],
  'moco_integration_field_name' => [
    'name' => 'moco_integration_field_name',
    'type' => 'String',
    'html_type' => 'select',
    'default' => '',
    'title' => ts('MOCO ID Field'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Custom field for MOCO IDs'),
  ],
  'moco_integration_id_type' => [
    'name' => 'moco_integration_id_type',
    'type' => 'String',
    'html_type' => 'select',
    'default' => 'company',
    'title' => ts('MOCO ID Type'),
    'is_domain' => 1,
    'is_contact' => 0,
    'options' => [
      'company' => ts('Company ID'),
      'contact' => ts('Contact ID')
    ],
  ],
  'moco_integration_cache_enabled' => [
    'name' => 'moco_integration_cache_enabled',
    'type' => 'Boolean',
    'html_type' => 'checkbox',
    'default' => TRUE,
    'title' => ts('Enable Caching'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
  'moco_integration_cache_ttl' => [
    'name' => 'moco_integration_cache_ttl',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 300,
    'title' => ts('Cache TTL'),
    'is_domain' => 1,
    'is_contact' => 0,
  ],
];
